changes

diff --git a/bin/gvm b/bin/gvm
--- a/bin/gvm
+++ b/bin/gvm
@@ -1,13 +1,6 @@
 #!/usr/bin/env bash
 
-## Functions/
-
-is_in_use() {
-  [[ -e "$1/.git/index.lock" || -e "$1/.hg/store/lock"  || -e "$1/.bzr/checkout/lock" ]]
-}
-
-# Iterates over Godep file dependencies and sets
-# the specified version on each of them.
+# Iterates over Godep file dependencies and sets the specified version on each of them.
 set_dependencies() {
   local deps=$(sed 's/#.*//;/^\s*$/d' < $1) || echo ""
 
@@ -21,16 +14,9 @@ set_dependencies() {
 
   while read package version; do
     (
-      local pkg_path=$(echo "$package" | awk -F/ '{print $1"/"$2"/"$3}')
-      local install_path="${GOPATH%%:*}/src/${pkg_path%%/...}"
       echo ">> Setting $package to version $version"
-      cd $install_path
-      is_in_use $install_path && wait
-
-      [ -d .bzr ] && bzr revert   -q -r   "$version"
-      [ -d .git ] && git checkout -q      "$version"
-      [ -d .hg  ] && hg update    -q      "$version"
-      [ -d .svn ] && svn update   -r      "$version"
+      local pkg_path=$(echo "$package" | awk -F/ '{print $1"/"$2"/"$3}')
+      set_package_to_version $pkg_path "$version"
     ) &
   done < <(echo "$deps")
   wait
@@ -38,15 +24,21 @@ set_dependencies() {
 }
 
 link() {
-  folder=".godeps/src/$1"
-  cont=$(dirname "$folder")
-  pwd=$(pwd)
-  dest=${2:-$pwd}
+  to=$1
+  from=${2:-$PWD}
+  echo "From: $from"
 
-  [[ ! -d $cont ]] && mkdir -p $cont
-  [[ -d $folder ]] && echo "Exists" && exit 1
+  [[ -d "$from" ]] || return
 
-  ln -vs $dest $folder
+  echo ">> Linking $from/* to $to"
+
+  [[ ! -d $to ]] && mkdir -p $to
+  for f in $from/*; do 
+    [[ "$f" =~ "Godeps" || "$f" =~ ".godeps" ]] && continue
+    bf=$(basename $f)
+    echo ">> Linking $from/$bf to $to/$bf..."
+    ln -vs $from/$bf $to/$bf
+  done
 }
 
 bootstrap() {
@@ -56,180 +48,155 @@ bootstrap() {
 
   while read package; do
     (
-      version=`find_last_tag_or_HEAD "$package"`
-      [ -n "$version" ] && (
-        echo ">> Adding package "$package" version "$version" to Godeps."
-        echo ""$package" "$version"" >> Godeps
-        set_package_to_version $package $version
-      )
-    ) &
+      package_and_version=`find_package_and_last_tag_or_head "$package"`
+      IFS=" " read p v <<< $package_and_version
+      echo ">> Adding package "$p" version "$v" to Godeps."
+      echo ""$p" "$v"" >> Godeps
+      set_package_to_version $p $v
+    )
   done < <(echo "$dependencies")
 
   wait
+  sort -u -o Godeps Godeps
   echo ">> All Done."
 }
 
-## Sets a given package to a given revision using
-## the appropriate VCS.
-#
+# Sets a given package to a given revision using the appropriate VCS.
 set_package_to_version() {
   cd "${GOPATH%%:*}/src/${1%%/...}"
 
-  ## Avoid multiple processes messing with the same
-  ## package at the same time.
-  [[ -e "$PWD/.git/index.lock" ||
-  -e "$PWD/.hg/store/lock" ||
-  -e "$PWD/.bzr/checkout/lock" ]] && wait
+  [[ -e "$PWD/.git/index.lock" || -e "$PWD/.hg/store/lock"  || -e "$PWD/.bzr/checkout/lock" ]] && wait
 
   [ -d .hg ]  && hg update    -q      "$2"
   [ -d .git ] && git checkout -q      "$2"
   [ -d .bzr ] && bzr revert   -q -r   "$2"
 }
 
-## Returns the latest tag (or, failing that latest revision)
-## for an installed package.
-#
-find_last_tag_or_HEAD() {
-  cd "${GOPATH%%:*}/src/${1%%/...}"
+find_package_and_last_tag_or_head() {
+  folder="${GOPATH%%:*}/src/${1%%/...}"
+  tmp=$folder
+  cd $folder
 
-  ## If no repo file is found it means we are inside a repo's
-  ## subdirectory tree, we can just ignore this package.
-  [ ! -d .git ] && [ ! -d .bzr ] && [ ! -d .hg ] &&
-    echo ">> Ignored $1, not top-level package." 1>&2 && return
+  # If no repo file is found it means we are inside a repo's subdirectory tree, we can just ignore this package.
+  while [ ! -d .git ] && [ ! -d .bzr ] && [ ! -d .hg ]; do
+    tmp=$(dirname $tmp)
+    cd $tmp
+  done
+  echo ">> Found root package $tmp" 1>&2
 
+  [[ -e "$PWD/.git/index.lock" || -e "$PWD/.hg/store/lock"  || -e "$PWD/.bzr/checkout/lock" ]] && wait
+
+  real_package="${tmp##$GOPATH/src/}"
   [ -d .git ] && (
     # FIXME: there should be a better way,  but git tags returns in alphabetical order.
-    version=`git tag |
-            xargs -I@ git log --format=format:"%ai @%n" -1 @ |
-            sort |
-            awk '{print $4}' |
-            tail -1`
-
-
-    [ -n "$version" ] && echo "$version" && return
-
+    version=`git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}' | tail -1`
+    [ -n "$version" ] && echo "$real_package $version" && return
     version=`git log -n 1 --pretty=oneline | cut -d " " -f 1`
     echo ">> No tags on package "$1", setting version to latest revision." 1>&2
-    echo "$version" && return
+    echo "$real_package $version" && return
   )
 
   [ -d .bzr ] && (
     version=`bzr tags | tail -1 | cut -d " " -f 1`
-    [ -n "$version" ] && echo "$version" && return
-
+    [ -n "$version" ] && echo "$real_package $version" && return
     version=`bzr log -r-1 --log-format=line | cut -d ":" -f 1`
     echo ">> No tags on package "$1", setting version to latest revision." 1>&2
-    echo "$version" && return
+    echo "$real_package $version" && return
   )
 
   [ -d .hg ] && (
     version=`hg parents --template "{latesttag}"`
-
-    [ "$version" != "null" ] && echo "$version" && return
-
+    [ "$version" != "null" ] && echo "$real_package $version" && return
     version=`hg log --template "{node}" -l 1`
     echo ">> No tags on package "$1", setting version to latest_revision." 1>&2
-    echo "$version" && return
+    echo "$real_package $version" && return
   )
 
   echo " "
 }
 
-godeps_build() {
+deps_build() {
   local deps=$(sed 's/#.*//;/^\s*$/d' < $1) || echo ""
-
   while read package version; do
-    go_install $package
+    echo ">> Pre-building $package/..."
+    go install $package/...
+    echo ">> Pre-building $package"
+    go install $package
   done < <(echo "$deps")
-}
-
-godeps_git_build() {
-  local deps=$(sed 's/#.*//;/^\s*$/d' < $1) || echo ""
-
-  while read repo package version; do
-    go_install $package
-  done < <(echo "$deps")
-}
-
-go_install() {
-  local package=$1
-  echo ">> Pre-building $package/..."
-  go install $package/...
-  echo ">> Pre-building $package"
-  go install $package
 }
 
 ## /Functions
 
+usage() {
+cat << EOF
+SYNOPSIS
+
+    A Godeps file in the root of your Go application is expected containing
+    the import paths of your packages and a specific tag or commit hash
+    from its version control system, an example Godeps file looks like this:
+
+    $ cat Godeps
+    # This is a comment
+    github.com/nu7hatch/gotrail         v0.0.2
+    github.com/replicon/fast-archiver   v1.02   #This is another comment!
+    github.com/nu7hatch/gotrail         2eb79d1f03ab24bacbc32b15b75769880629a865
+
+USAGE
+      Version information
+      $ gvm version
+
+      Parses all the go package dependencies, saves them into the Godeps file&
+      $ gvm bootstrap 
+
+      Set the package name and make a symlink
+      $ gvm self github.com/test/test
+
+      Parses the Godeps file, installs dependencies and sets them to the appropriate version.
+      $ gvm install
+
+      Builds all the dependencies
+      $ gvm prebuild
+EOF
+}
+
 ## Command Line Parsing
+(which go > /dev/null) || ( echo ">> Go is currently not installed or in your PATH" && exit 1)
+
 case "${1:-"install"}" in
+  "help")
+    usage
+    ;;
   "version")
-    echo ">> gvm v1.0"
+    echo ">> gvm v0.1"
     ;;
   "install")
     deps_file="${2:-"Godeps"}"
     [[ -r "$deps_file" ]] || (echo ">> $deps_file file does not exist." && exit 1)
-    (which go > /dev/null) ||
-      ( echo ">> Go is currently not installed or in your PATH" && exit 1)
-    set_dependencies $deps_file
+    GOPATH=$(PWD)/.godeps set_dependencies $deps_file
     ;;
   "prebuild")
-    case "${2}" in
-      "build")
-        (which go > /dev/null) ||
-          ( echo ">> Go is currently not installed or in your PATH" && exit 1)
-        if [ ! -z "${3:-}" ]; then
-          [[ -f "$3" ]] || (echo ">> $3 file does not exist." && exit 1)
-          if [ $(expr $(cat "$3" | head -n 1 | grep -o " " | wc -l)) -eq 1 ]; then
-            # Godeps
-            godeps_build "$3"
-          # elif [ $(expr $(cat "$2" | head -n 1 | grep -o " " | wc -l)) -eq 2 ]; then
-          #   # Godeps-Git
-          #   godeps_git_build "$2"
-          else
-            echo ">> $3 file is not in Godeps or Godeps-Git format." && exit 1
-          fi
-        else
-          godeps_file="Godeps"
-          [[ -f $godeps_file ]] ||
-            (echo ">> $godeps_file does not exist." && exit 1)
-          [[ -f $godeps_file ]] && godeps_build $godeps_file
-        fi
-        wait
-        echo ">> All Done"
-        ;;
-      "clean")
-        rm -rf ${GOPATH%%:*}/pkg/*
-        ;;
-    esac ;;
-  "local")
-    case "${2}" in
-      "name")
-        [[ "${3:-""}" == "" ]] && exit 1
-        ln_path="${GOPATH%%:*}/src/${3}"
-        ln_base=$(dirname "${GOPATH%%:*}")
-        echo ">> Linking $ln_base to $ln_path"
-        mkdir -p $(dirname "$ln_path")
-        ln -s "$ln_base" "$ln_path"
-        ;;
-    esac ;;
-  "link")
-    case "${2}" in
-      "add")
-        [[ -z $3 ]] && exit 1
-        link $3 $4
-        ;;
-      "del")
-        [[ -z $3 ]] && exit 1
-        folder=".godeps/src/$3"
-        [[ -d "$folder" ]] && rm -rf $folder
-
-        echo ">> $folder removed"
-        ;;
-    esac ;;
+    godeps_file="Godeps"
+    [[ -f $godeps_file ]] || (echo ">> $godeps_file does not exist." && exit 1)
+    [[ -f $godeps_file ]] && GOPATH=$(PWD)/.godeps deps_build $godeps_file
+    wait
+    echo ">> All Done"
+    ;;
+  "test")
+    for f in ./*; do 
+      [[ "$f" =~ "Godeps" || "$f" =~ ".godeps" ]] && continue
+      #( file "$PWD/$f" | grep "executable" ) || continue
+      echo $(basename $f)
+      [[ -d "$f" ]] && echo ">> Linking .godeps/src/$2/$f to $f"
+      [[ -f "$f" ]] && echo "linking file .godeps/src/$2/$f to $f"
+    done
+    ;;
+  "self")
+    [[ "${2:-""}" == "" ]] && exit 1
+    echo ">> Setting package name to $2"
+    link ".godeps/src/${2}"
+    ;;
   "bootstrap")
-    [[ -f "Godeps" ]] &&
-      echo ">> A Godeps file exists within this directory." && exit 1
+    [[ -f "Godeps" ]] && echo ">> A Godeps file exists within this directory." && exit 1
     mkdir -p .godeps/{src,pkg,bin}
     bootstrap
     if [ ! -z "${2:-}" ]; then
@@ -241,15 +208,14 @@ case "${1:-"install"}" in
     if [[ -n $GVM_NAME ]]; then
       echo ">> Already set path to $GOPATH, exiting..."
       do=0
-      #kill -INT $$;
     fi
 
+    mkdir -p .godeps/{src,pkg,bin}
     GVM_DIR="$(pwd)/.godeps"
 
     if [[ ! -d $GVM_DIR ]]; then
-      echo '>> Directory .godeps not found. Run `gvp init` first.'
+      echo '>> Directory .godeps not found. Run `gvm init` first.'
       do=0
-      #kill -INT $$
     fi
 
     if [ "$do" -eq "1" ]; then
@@ -267,6 +233,7 @@ case "${1:-"install"}" in
       echo ">> Local GOPATH set."
 
       if [[ -n $2 ]]; then
+        echo ">> Running ${@:2}"
         eval ${@:2}
       fi
     fi
